language: java
sudo: false
addons:
  sonarcloud:
    organization: "vlad-iv-github"
    token:
      secure: "$SONAR_TOKEN"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
script:
  - mvn -version
  - mvn clean install sonar:sonar -Psonar -Pjacoco --errors --batch-mode
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
after_success:
  - "bash <(curl -s https://codecov.io/bash)"