version: '{build}'
branches:
  only:
    - master
skip_tags: true
init:
  - git config --global core.autocrlf true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11
os: Windows Server 2012
install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-Xmx4g
  - cmd: SET JAVA_OPTS=-Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -Dmaven.test.skip=true
test_script:
  - mvn clean install -Pspotbugs --batch-mode
cache:
  - C:\Users\appveyor\.m2